### PR TITLE
[C++] Fixed the Number of Variables (was showing wrong)

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Reference: 
* https://github.com/Open-Sourced-Olaf/Code-Kindle/issues/8#issuecomment-821754741 

## After Changes:

image

### CODE REVIEW

**Comment by anjalisoni3655** [comment]
> ## Reference: 
> * https://github.com/Open-Sourced-Olaf/Code-Kindle/issues/8#issuecomment-821754741 
> 
> ## After Changes:
> 
> image
> 
> 
> 

cpp-pseudogen/main.exe this file should not be committed to GitHub. Please add this gitignore.

**Comment by Siddhant-K-code** [comment]
> Please add this gitignore.

i think i should add `.gitingore` for C++/Python, i think `backend/db.sqlite3` is also not needed

**Comment by Siddhant-K-code** [comment]
@anjalisoni3655 Please review and merge!

**Review by anjalisoni3655 — APPROVED** [review]
Code needs a lot of refactoring it seems, there are other files committed to GitHub that are not required.

**Pull request merged**
