### PR TITLE
Added Codacy Analysis CLI Action

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
Reference: https://github.com/Open-Sourced-Olaf/Code-Kindle/issues/42#issuecomment-821788090

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
@anjalisoni3655 Please Review and Merge!

**Comment by Siddhant-K-code** [comment]
there is some problem with this setup, file should be like this : 

```yaml
name: Codacy Security Scan

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          output: results.sarif
          format: sarif
          # Adjust severity of non-security issues
          gh-code-scanning-compat: true
          # Force 0 exit code to allow SARIF file generation
          # This will handover control about PR rejection to the GitHub side
          max-allowed-issues: 2147483647
      
      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif
```

because actions/checkout is no more using master, they are using main. Pls edit it if you can @anjalisoni3655

**Comment by anjalisoni3655** [comment]
> there is some problem with this setup, file should be like this : 
> 
> ```yaml
> name: Codacy Security Scan
> 
> on:
>   push:
>     branches: [ "master", "main" ]
>   pull_request:
>     branches: [ "master", "main" ]
> 
> jobs:
>   codacy-security-scan:
>     name: Codacy Security Scan
>     runs-on: ubuntu-latest
>     steps:
>       - name: Checkout code
>         uses: actions/checkout@main
> 
>       - name: Run Codacy Analysis CLI
>         uses: codacy/codacy-analysis-cli-action@master
>         with:
>           output: results.sarif
>           format: sarif
>           # Adjust severity of non-security issues
>           gh-code-scanning-compat: true
>           # Force 0 exit code to allow SARIF file generation
>           # This will handover control about PR rejection to the GitHub side
>           max-allowed-issues: 2147483647
>       
>       # Upload the SARIF file generated in the previous step
>       - name: Upload SARIF results file
>         uses: github/codeql-action/upload-sarif@main
>         with:
>           sarif_file: results.sarif
> ```
> 
> because actions/checkout is no more using master, they are using main. Pls edit it if you can @anjalisoni3655 

Can you please create an issue for this and raise a new PR. I couldn't run the checks before merging.

**Comment by Siddhant-K-code** [comment]
creating new PR, let checks will be passed first.

**Pull request merged**
